# Generated by Django 3.2.1 on 2024-07-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20240709_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(default='no_cover.png', null=True, upload_to=''),
        ),
    ]
