# Generated by Django 3.2.1 on 2024-07-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20240709_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='room',
            new_name='book',
        ),
    ]
